routes/web.php
<?php

Route::redirect('/', 'admin/home');

Auth::routes(['register' => false]);

Route::group(['middleware' => ['checkstatus']], function () {
    Route::post('/login', 'Auth\LoginController@login');
});

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/news', 'NewsController@index')->name('news.index');
    Route::get('/news/{id}', 'NewsController@view')->name('news.view');
    Route::get('/delete/{id}', 'NewsController@delete')->name('news.delete');
    Route::get('/download/zip/{id}', 'NewsController@downloadZip')->name('news.downloadZip');

    
    // settings
    Route::get('settings/general', 'Admin\SettingsController@index')->name('settings.general');
    Route::get('storage/link', 'Admin\SettingsController@storageLink')->name('storage.link');
    Route::post('settings/general/save', 'Admin\SettingsController@save')->name('settings.general.save');

});

Route::get('download', 'NewsController@download')->name('app.download');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $table = 'news';
    protected $guarded = [];

    public function media()
    {
        return $this->hasMany(Media::class, 'news_id', 'id');
    }

    public static function storeNews($data)
    {
        $news = News::create($data);

        return $news;
    }

    public static function getNews($perPage = false)
    {
        $news = News::with(['media']);
        if ($perPage) {
            $res = $news->paginate($perPage);
        } else {
            $res = $news->orderBy('created_at','desc')->get();
        }
        return $res;
    }

    public static function getOne($id){
        return News::where('id',$id)->with(['media'])->first();
    }
    public static function deleteNews($id){
        return News::where('id',$id)->delete();
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Media;
use App\News;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class NewsController extends Controller
{
    public function index()
    {
        $news = News::getNews();
        return view('news.index')
            ->with('news',$news);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),
            [
                'title' => 'required',
                'description' => 'required',
            ]);

        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()], 401);
        }
        $data = [
            'title' => $request->title,
            'description' => $request->description,
            'comment' => $request->comment,
            'created_by' => 1,
            'created_at' => Carbon::now()
        ];
        $savedNews = News::storeNews($data);
        $this->storeMedia($request, $savedNews->id);

        if ($savedNews){
            return response()->json([
                "success" => true,
                "message" => "News Uploaded Successfully!",
            ]);
        }

    }

    private function storeMedia($request,$newsId)
    {
        Log::info(json_encode($request->all()));
        Log::info(json_encode($request->file('files')));
//        if($request->file('files') && count($request->file('files'))){


            foreach ($request->file('files') as $file){
//        for ($x = 1; $x < 10; $x++) {
//            if ($request->hasFile('file_'.$x)){
//                $file = $request->file('file_'.$x);
                $ext = $file->extension();
                $path = 'media';
                $file_name = time() . rand(10000, 100000) . $file->extension() . '.' . $ext; //create file name
                $file->move('./' . $path, $file_name); //path to save file
                $file_path = $path . '/' . $file_name;
                $file_type = 'image';

                $data = [
                    'news_id' => $newsId,
                    'file_name' => $file_name,
                    'file_path' => $file_path,
                    'file_type' => $file_type,
                    'file_ext' => $ext,
                    'created_by' => 1,
                    'created_at' => Carbon::now()
                ];

                Media::storeMedia($data);
            }
//        }
//            }
//        }
    }

    public function downloadZip($id){
        $zip = new \ZipArchive();
        $news = News::getOne($id);
        $newsTitle = preg_replace('/[^A-Za-z0-9\-]/', '', $news->title).'-'.Carbon::parse($news->created_at)->format('Y-m-d').'-'.rand(100,1000);
        $zip_file = $newsTitle.'.zip';

        if ($zip->open($zip_file, \ZipArchive::CREATE | \ZipArchive::OVERWRITE) !== TRUE) {
            echo 'Could not open ZIP file.';
            return;
        }

        $mediaList = Media::getMedia($id)->pluck('file_path')->toArray();

        $newsContent = '';
        $newsContent .= "##News Title: \n\n";
        $newsContent .= $news->title . "\n\n";
        $newsContent .= "##News Description: \n\n";
        $newsContent .= $news->description . "\n\n";
        $newsContent .= "##News Comments: \n\n";
        $newsContent .= $news->comment . "\n\n";
        $newsContent .= "##News Media: \n\n";
        $newsContent .= count($mediaList) . " (attached ZIP file)\n\n";

        $txtFile = Storage::disk('public')->put('contents/'.$newsTitle.'.txt', $newsContent);
        $txtFilePath = 'storage/contents/'.$newsTitle.'.txt';

        // Add File in ZipArchive
        if (count($mediaList)){

            foreach($mediaList as $file)
            {
                if (! $zip->addFile($file, basename($file))) {
                    echo 'Could not add file to ZIP: ' . $file;
                }
            }

        }

        if ($txtFile){
            $zip->addFile($txtFilePath, $newsTitle.'.txt');
        }
        // Close ZipArchive
        $zip->close();

        return response()->download($zip_file);
//        rename($tempFileUri, 'zipPathAndName');
    }

    public function download()
    {
        return view('download');
    }

    public function view($id)
    {
        $news = News::getOne($id);
        return view('news.view')
            ->with('news', $news);
    }

    public function delete($id)
    {
        $news = News::deleteNews($id);
        if ($news) {
            Media::deleteMedia($id);
            session()->flash('message', "News Deleted Successfully!");

        } else {
            session()->flash('error', "something went wrong!");
        }

        return redirect()->route('admin.news.index');
    }
}

resources/views/news/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
            Manage News
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                    <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            News Title
                        </th>
                        <th>
                            News Description
                        </th>
                        <th>
                            Comment
                        </th>
                        <th>
                            Media
                        </th>
                        <th>
                            Reported At
                        </th>
                        <th>
                            Download Zip
                        </th>

                    </tr>
                    </thead>
                    <tbody>
                    @if(count($news))
                        @foreach($news as $newsSingle)
                            <tr>
                                <td></td>
                                <td>{{$newsSingle->title}}</td>
                                <td>{{\Illuminate\Support\Str::limit($newsSingle->description,50,' ...')}}</td>
                                <td>{{$newsSingle->comment}}</td>
                                <td>
                                    @if(count($newsSingle->media))
                                        <div>
                                            @foreach($newsSingle->media as $media)
                                                <img src="{{asset($media->file_path)}}" alt="" width="50px">
                                            @endforeach
                                        </div>
                                    @else
                                        <b>-</b>
                                    @endif
                                </td>
                                <td>{{\Carbon\Carbon::parse($newsSingle->created_at)->diffForHumans()}}</td>
                                <td>
                                    <a href="{{ route('admin.news.view', $newsSingle->id) }}" class="btn btn-primary"
                                       title="View News">
                                        <i class="nav-icon fas fa-fw fa-eye">
                                        </i>
                                    </a>
                                    <a class="" title="Download as Zip"
                                       href="{{ route('admin.news.downloadZip', $newsSingle->id) }}">
                                        <img src="{{asset('images/zip.png')}}" width="20%">
                                    </a>
                                    <a href="{{ route('admin.news.delete', $newsSingle->id) }}" class="btn btn-primary"
                                       title="Delete News">
                                        <i class="nav-icon fas fa-fw fa-trash">
                                        </i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>


        </div>
    </div>
@endsection
@section('scripts')
    @parent
    <script>
        $(function () {
            let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)

            $.extend(true, $.fn.dataTable.defaults, {
                // order: [[5, 'desc']],
                pageLength: 100,
            });
            $('.datatable-User:not(.ajaxTable)').DataTable({buttons: dtButtons})
            $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                $($.fn.dataTable.tables(true)).DataTable()
                    .columns.adjust();
            });
        });

    </script>
@endsection

resources/views/news/view.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-10">
                    <h3 class="w-75">View News</h3>
                </div>
                <div class="col-md-2 text-right">
                    <a href="{{ route('admin.news.downloadZip', $news->id) }}" class="btn btn-info"
                       title="Download as Zip">ZIP</a>
                    <a href="{{ route('admin.news.delete', $news->id) }}" class="btn btn-danger"
                       style="margin-left: 5px" title="Delete News">Delete</a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h5>News Title</h5>
                            <p>{{$news->title}}</p>
                            <br>
                            <h5>News Description</h5>
                            <p>{{$news->description}}</p>
                            <br>
                            <h5>News Comment</h5>
                            <p>{{$news->comment}}</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h5>News Media</h5>
                            @if(count($news->media))
                                @foreach($news->media as $media)
                                    <img src="{{asset($media->file_path)}}" alt="" width="25%" style="
                                    padding: 8px;
                                    box-shadow: 0px 0px 13px 0px #999;
                                    border-radius: 10px;
                                ">

                                @endforeach
                            @else
                                <p class="text-center" style="background:#eee">
                                    No image found
                                </p>
                            @endif

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection
@section('scripts')
    @parent

@endsection